### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ericdrosado** [mittal-parth/Inventory-Management-Django#7]
A README is often the first item a visitor will see when visiting your repository. We recommend that your README has:
* How to [contribute to your project](https://docs.github.com/en/get-started/quickstart/contributing-to-projects)
* A section mentioning your code of conduct

**Comment by mittal-parth** [comment]
Hi @ericdrosado! 
Added a contributing section to the readme via #18. 
Sorry for the delay!
